version: '3.9'
services:
    my_app:
      depends_on: 
        - postgres_db
      build:
          context: ./web
          dockerfile: Dockerfile 
      image: django-k8s-image:v1
      env_file:
        - web/.env
      environment:
        - PORT=8020
      ports:
        - 8002:8020
      command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
      postgres_db:
        image: postgres
        env_file:
          - web/.env
        expose: 
          - 5432
        volumes:
          - postgres_data: 'var/lib/postgresql/data'

volumes:
  postgres_data:
        
